name: Full Test CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - uses: actions/checkout@v4

    # ------------------------
    # Backend (Java) Testing
    # ------------------------
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Use the Temurin distribution of OpenJDK
        java-version: '17'       # Set the Java version (you can use a different version if needed)

    - name: Install Maven
      run: sudo apt-get install maven -y

    - name: Build Backend with Maven
      run: |
        cd backend
        mvn clean install

    # Run specific tests in the root directory
    - name: Run tests in the root directory
      run: |
        # Run specific test classes in the root directory
        mvn -Dtest=LoginServletTest test

    # Display the content of LoginServletTest.java test results
    - name: Display test results
      run: |
        if [ -f target/surefire-reports/TEST-LoginServletTest.xml ]; then
          cat target/surefire-reports/TEST-LoginServletTest.xml
        else
          echo "Test result file not found."
        fi
