name: Full Test CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # ------------------------
      # Backend (Java) Testing
      # ------------------------
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use the Temurin distribution of OpenJDK
          java-version: '1.8'      # Set the Java version to 1.8 to match the pom.xml

      - name: Install Maven
        run: sudo apt-get install maven -y

      - name: Build Backend with Maven
        run: |
          cd backend
          mvn clean install

      - name: Run Backend Tests
        run: |
          cd backend
          mvn test

      - name: Display Backend Test File
        run: |
          cat backend/src/test/java/LoginServletTest.java

